# Generated by Django 5.0.4 on 2024-08-23 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccomment',
            name='comment_ptr',
        ),
        migrations.RemoveField(
            model_name='topiccomment',
            name='topic',
        ),
        migrations.AlterField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='topic_disliked', to=settings.AUTH_USER_MODEL, verbose_name='Dislikes'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='topic_liked', to=settings.AUTH_USER_MODEL, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.CreateModel(
            name='TopicReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Nota mínima é 0'), django.core.validators.MaxValueValidator(10, 'Nota máxima é 10')], verbose_name='Avaliação')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_review', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='topic_reviews_disliked', to=settings.AUTH_USER_MODEL, verbose_name='Dislikes')),
                ('likes', models.ManyToManyField(blank=True, related_name='topic_reviews_liked', to=settings.AUTH_USER_MODEL, verbose_name='Likes')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='forum.topic', verbose_name='Tópico')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='TopicComment',
        ),
    ]
