# Generated by Django 5.0.4 on 2024-08-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_topiccomment_comment_ptr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicreview',
            name='rating',
        ),
    ]
